version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - BACKEND_BASE_URL=https://foodie-backend.manjurulhoque.com
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=https://foodie.manjurulhoque.com
    restart: unless-stopped

  nginx:
    build: ./deployment/nginx
    ports:
      - "3000:80"
    depends_on:
      - frontend
    restart: unless-stopped 