version: '3.8'

services:
  frontend:
    container_name: foodie-frontend
    image: foodie-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - BACKEND_BASE_URL=http://foodie-backend.manjurulhoque.com
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://foodie.manjurulhoque.com
    restart: unless-stopped
    networks:
        - foodie-network

  nginx:
    container_name: foodie-frontend-nginx
    image: foodie-frontend-nginx
    build: ./deployment/nginx
    ports:
      - "82:80"
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
        - foodie-network

networks:
    foodie-network:
