import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className={cn("bg-background antialiased", urbanist.variable)}>
          <img
            src="/img/hero.svg"
            className="absolute -z-10 top-0 right-0 w-full md:w-[60%]"
            alt="hero-svg"
          />

          {children}
        </body>
      </html>
  );
}
